stages:
  - test
  - web

default:
  tags:
    - ogm
  before_script:
    - dmd --version | sed -n 1p
    - ldc2 --version | sed -n 1p
    - dub --version

.test:
  stage: test
  artifacts:
    when: always
    paths:
      - .trial
    reports:
      junit: .trial/xunit/*.xml

test-dmd:
  extends: .test
  script:
    - dub test --compiler=dmd

test-ldc:
  extends: .test
  script:
    - dub test --compiler=ldc2

examples:
  stage: test
  script:
    - (cd examples/spec && dub test --compiler=dmd)
    - (cd examples/unittest && dub test --compiler=dmd)

pages:
  stage: web
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - test-dmd
  script:
    - dub build -b ddox --compiler=dmd
    - cd website
    - npm ci
    - npm run build
    - npm run build:api
    - mv dist ../public
    - cd ..
    - mv .trial public/artifacts
    - mv public/artifacts/allure public/artifacts/allure-raw
    - npx --yes allure-commandline@1.4.23 generate --output public/artifacts/allure public/artifacts/allure-raw
  artifacts:
    paths:
      - public
